### ISSUE TITLE
macOS nightly build does not include QT

### ISSUE THREAD

**Issue by sslupsky** [sigrokproject/pulseview#68]
When I attempt to run pulseview on macOS 14.4.1 it generate an exception on launch.

It looks like the nightly build does not include the QT libs.

```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               pulseview.real [3830]
Path:                  /Applications/pulseview.app/Contents/MacOS/pulseview
Identifier:            pulseview.real
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-04-03 11:15:04.9061 -0600
OS Version:            macOS 14.4.1 (23E224)
Report Version:        12
Anonymous UUID:        165CAC07-929C-D0C1-88B1-90A0C62650C1


Time Awake Since Boot: 11000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @rpath/QtDBus.framework/Versions/A/QtDBus
Referenced from: <7F9EB672-8564-3C87-90D9-168BD8004626> /Applications/pulseview.app/Contents/Frameworks/QtGui.framework/Versions/A/QtGui
Reason: tried: '/Applications/pulseview.app/Contents/Frameworks/QtGui.framework/Versions/A/../../../QtDBus.framework/Versions/A/QtDBus' (no such file), '/Applications/pulseview.app/Contents/Frameworks/QtWidgets.framework/Versions/A/../../../QtDBus.framework/Versions/A/QtDBus' (no such file), '/Library/Frameworks/QtDBus.framework/Versions/A/QtDBus' (no such file), '/System/Library/Frameworks/QtDBus.framework/Versions/A/QtDBus' (no such file, not in dyld cache)Library not loaded: /usr/local/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/Python
Referenced from: <3E9631A5-B63C-38F9-AB26-7E3B8F42A221> /Applications/pulseview.app/Contents/Frameworks/libsigrokdecode.4.dylib
Reason: tried: '/usr/local/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/Python' (no such file), '/System/Volumes/Pre
(terminated at launch; ignore backtrace)
```

**Comment by Murmele** [comment]
I have seen the same problem on windows: http://sigrok.org/bugzilla/show_bug.cgi?id=1892

**Comment by pskowronek** [comment]
I confirm, got the same on today nightly build. 
Stable version 0.4.2 works fine.

macOS: Ventura 13.6.6

**Comment by sugarthc** [comment]
Also it appears that the bundled libsigrokdecode.dylib is attempting to load a version of python that is not the one in the bundled frameworks:

Library not loaded: /usr/local/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/Python
Referenced from: <3E9631A5-B63C-38F9-AB26-7E3B8F42A221> /Volumes/*/pulseview.app/Contents/Frameworks/libsigrokdecode.4.dylib
Reason: tried: '/usr/local/opt/python@3.12/Frameworks/Python.framework/Versio
(terminated at launch; ignore backtrace)
...

$ otool -L ./pulseview.app/Contents/Frameworks/libsigrokdecode.4.dylib 
libsigrokdecode.4.dylib:
	@executable_path/../Frameworks/libsigrokdecode.4.dylib (compatibility version 5.0.0, current version 5.0.0)
	@executable_path/../Frameworks/libglib-2.0.0.dylib (compatibility version 7801.0.0, current version 7801.4.0)
	@executable_path/../Frameworks/libintl.8.dylib (compatibility version 13.0.0, current version 13.0.0)
	/usr/local/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/Python (compatibility version 3.12.0, current version 3.12.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)

**Comment by sugarthc** [comment]
It seems that most of the Qt libs are present, the exception being the QtDBus noted in the original report.

**Comment by sugarthc** [comment]
and just for completeness so that several iterations are not needed for these issues.  The bundled libzip dylib is trying to load libraries not from the bundled location:

$ otool -L pulseview.app/Contents/Frameworks/libzip.5.dylib 
libzip.5.dylib:
	@executable_path/../Frameworks/libzip.5.dylib (compatibility version 5.0.0, current version 5.5.0)
	/usr/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.8)
	@loader_path/../../../../opt/xz/lib/liblzma.5.dylib (compatibility version 10.0.0, current version 10.4.0)
	@loader_path/../../../../opt/zstd/lib/libzstd.1.dylib (compatibility version 1.0.0, current version 1.5.5)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)

The liblzma and libzstd dylibs should be loaded from the bundled location.

**Comment by hellvesper** [comment]
Is there workaround?

**Comment by Joebeazelman** [comment]
Is there a workaround or solution?  The error is still persistent.

**Comment by abraxa** [comment]
Have you tried the recent builds?

**Comment by hellvesper** [comment]
> Have you tried the recent builds? My understanding is that they work.

Indeed, just checked, latest nightly works, finally great news!

**Comment by abraxa** [comment]
Thank you, I'll close this issue then.
