### ISSUE TITLE
Android nightly apk unavailable in site

### ISSUE THREAD

**Issue by MangyCat** [sigrokproject/pulseview#69]
I was gonna go download pulseview for my phone, but the apk is not accessible.
site: [Wiki](https://www.sigrok.org/wiki/Android)
![image](https://github.com/sigrokproject/pulseview/assets/73955445/ddd9cf93-686b-4f1c-afe0-c746402c6d2f)
![image](https://github.com/sigrokproject/pulseview/assets/73955445/6c1a967e-86a9-4d5b-ba37-fd21154949c1)

**Comment by abraxa** [comment]
Hello, the Android apk is currently unavailable as no one has been using it or maintaining it for a long time. If you're interested in doing so, please let me know.
