### ISSUE TITLE
Compile from source problem with storesession.cpp " cannot convert ‘Glib::DateTime’ to ‘Glib::TimeVal’ "

### ISSUE THREAD

**Issue by charkster** [sigrokproject/pulseview#70]
Hi am trying to compile Pulseview from source and am getting a compile error:

```
/home/xxxxx/pulseview/pv/storesession.cpp:188:96: error: cannot convert ‘Glib::DateTime’ to ‘Glib::TimeVal’
  188 |                 auto header = context->create_header_packet(session_.get_acquisition_start_time());
      |                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
      |                                                                                                |
      |                                                                                                Glib::DateTime
```

I looked more into this...
https://docs.gtk.org/glib/method.DateTime.to_timeval.html

It says something about the conversion is not safe for 2038 dates.
`GTimeVal is not year-2038-safe. Use g_date_time_to_unix() instead.`

Any ideas on how to get around this? I'm compiling the latest version on Ubuntu 24.04 using these instructions:
https://sigrok.org/gitweb/?p=pulseview.git;a=blob;f=INSTALL
Thanks.

**Comment by thierer** [comment]
You need to compile against a more recent `libsigrok`. `start_time`'s type [was changed in 2022](https://github.com/sigrokproject/libsigrok/commit/e446b3c461f88a85298fe6eec294b4906909c50b).

**Comment by charkster** [comment]
> You need to compile against a more recent `libsigrok`. `start_time`'s type [was changed in 2022](https://github.com/sigrokproject/libsigrok/commit/e446b3c461f88a85298fe6eec294b4906909c50b).

@thierer thank you for the response. I guess I will have to compile libsigrok first as the Ubuntu version is so out-of-date.

**Comment by a17r** [comment]
> [@thierer](https://github.com/thierer) thank you for the response. I guess I will have to compile libsigrok first as the Ubuntu version is so out-of-date.

I'll have to defend Ubuntu there: libsigrok has not made a release since 2019, and pulseview has not bumped minimum dependency beyond libsigrok-0.5.2 either.
