### ISSUE TITLE
What does the 'type' field in the decoder mean?

### ISSUE THREAD

**Issue by Antecer** [sigrokproject/pulseview#73]
What does the 'type' field in the decoder mean?
I can't find any relevant information in the decoder API wiki.
It looks llike this:
![QQ_1723353468299](https://github.com/user-attachments/assets/5e560bc3-209e-433f-86a7-b238700a269a)

It can show some logos on the waveform channel, but I have no idea what the type of numbers mean.
I'm trying to write a decoder myself, but this parameter is really bothering me.

**Comment by abraxa** [comment]
If you have questions about DSLogic products, please take it up with them, thanks.

https://github.com/DreamSourceLab/DSView/tree/master/libsigrokdecode4DSL/decoders/0-spi
