### ISSUE TITLE
Correct location to file bugs?

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [sigrokproject/pulseview#75]
https://github.com/sigrokproject/pulseview says:
> About
> Read-only mirror of the official repo at git://sigrok.org/pulseview. Pull requests welcome. Please file bugreports at sigrok.org/bugzilla.

However. 
* there is no way to create a new account on https://sigrok.org/bugzilla/. https://bugzilla.readthedocs.io/en/5.0.4/using/creating-an-account.html says there should be "On the home page, click the New Account link in the header.". I am not seeing that link.
* there are several issues open here.

What is the correct place?

Thanks.

**Comment by abraxa** [comment]
Hi Markus, bugzilla unfortunately was overrun by spam bots which keep creating tons of new accounts to post spam with when the registration is open to the public. For this reason, I unfortunately had to close registration at the moment.

Until this is resolved, feel free to report any issues you have with PulseView by coming on IRC to talk to us, opening an issue on github or sending a mail to the mailing list.
